neo4j:
    url: http://localhost:7474/db/data/
    
fb-api:
    access_token: 1552595251636325|BFcM3XfK-aYF6BlCiv27ByPqM4M

crawler:
    reset_graph: False 
    depth_level: 3
    root_sites:
        - revoltadosonline
        - mudancaja
        - MovimentoContraCorrupcao
        - mblivre
