neo4j:
    url: localhost:7474/db/data/
    user: neo4j
    password: 
    
fb-api:
    access_token: resources/fb-token

crawler:
    reset_graph: True
    depth_level: 4
    root_sites:
#        - impeachamentdilmarousseff
#        - 139414012895968
#        - 140140766087925
#        - 132086310159726
#        - lulanuncamais
#        - 717203835017729
#        - quadrilhadopt
#        - VemPraRuaBrasil.org
        - ColetivoMinervinodeOliveira
